In [17]:
import pandas as pd
import numpy as np

there are three main files:
opportunities
quotes 
leads

leads is for testing purposes

In [113]:
##############################
#load opportunities
opportunities = pd.read_csv('opportunities.csv')

In [19]:
opportunities.shape

(2499, 12)

In [36]:
opportunities.columns

Index(['Opportunity ID', 'Opportunity Name', 'Close Date', 'Created Date',
       'Stage', 'Billing Address Line 1', 'Billing Address Line 2',
       'Billing Address Line 3', 'Mailing Address Line 1',
       'Mailing Address Line 2', 'Opp Billing Address',
       'Opp Billing Address 2'],
      dtype='object')

In [35]:
opportunities.head(10)

,Opportunity ID,Opportunity Name,Close Date,Created Date,Stage,Billing Address Line 1,Billing Address Line 2,Billing Address Line 3,Mailing Address Line 1,Mailing Address Line 2,Opp Billing Address,Opp Billing Address 2
0,0061a00000GFpPA,Paradigm Properties LLC -TBD,9/30/16,8/10/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0061a00000GFwVj,Macklowe Properties - NYC - 1 Wall St.,9/30/16,8/12/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0061a00000G3m29,The Wolff Company - Portfolio,3/30/17,7/20/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0061a00000IuoBv,Paradigm Companies- Portfolio,6/30/17,4/25/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0061a00000IuMzU,Pittsburgh Sports & Exhibition Authority - PIT...,8/2/17,4/13/17,Lost,171 10th St.,NaN,NaN,200 Ross St.,4th Fl.,NaN,NaN
5,0061a00000Iuzsa,CBRE / GE - San Ramon - GE Digital Office,5/31/17,5/1/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0061a00000HyoAr,Brookfield - TBD,5/31/17,2/12/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0061a00000Iut45,Jones Lang LaSalle - Ireland-TBD,6/30/17,4/27/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0061a00000HvAWN,Ottawa Tourism - Wayfinding Ottawa,3/30/17,12/2/16,Lost,1405-150 Elgin Street,NaN,NaN,1405-150 Elgin Street,NaN,NaN,NaN
9,0061a00000G55iF,Historika - Zurich,10/3/16,8/1/16,Presentation,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
opportunities.Stage.value_counts()

Lost                 1466
Closed Won            375
Deal Signed           115
Qualified Lead        112
Presentation          107
Contract Sent          89
Proposal Sent          81
Invoice Sent           80
Research/Donation      58
Contract Expired        6
Pilot                   5
Contract Review         5
Name: Stage, dtype: int64

In [61]:
#1686 with no address
opportunities[opportunities['Mailing Address Line 1'].isnull()].shape

(1686, 12)

In [64]:
opportunities[opportunities['Billing Address Line 1'].isnull()==False].head()

,Opportunity ID,Opportunity Name,Close Date,Created Date,Stage,Billing Address Line 1,Billing Address Line 2,Billing Address Line 3,Mailing Address Line 1,Mailing Address Line 2,Opp Billing Address,Opp Billing Address 2
4,0061a00000IuMzU,Pittsburgh Sports & Exhibition Authority - PIT...,8/2/17,4/13/17,Lost,171 10th St.,NaN,NaN,200 Ross St.,4th Fl.,NaN,NaN
8,0061a00000HvAWN,Ottawa Tourism - Wayfinding Ottawa,3/30/17,12/2/16,Lost,1405-150 Elgin Street,NaN,NaN,1405-150 Elgin Street,NaN,NaN,NaN
12,0061a00000IuO8q,ConAm Group- SEA - Parla Apartments,5/1/17,4/13/17,Invoice Sent,3990 Ruffin Rd Ste 100,NaN,NaN,3990 Ruffin Rd Ste 100,NaN,NaN,NaN
13,0061a00000IuPVh,The ConAm Group-Location TBD,6/30/17,4/14/17,Lost,3990 Ruffin Rd Ste 100,NaN,NaN,3990 Ruffin Rd Ste 100,NaN,NaN,NaN
15,0061a00000IuSsn,Atlassian-Soma Offices,5/19/17,4/17/17,Closed Won,1098 Harrison St.,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
opportunities[opportunities['Mailing Address Line 1'].isnull()].Stage.value_counts()

Lost                 962
Closed Won           239
Qualified Lead        95
Presentation          90
Deal Signed           65
Proposal Sent         58
Invoice Sent          56
Contract Sent         55
Research/Donation     54
Pilot                  4
Contract Review        4
Contract Expired       4
Name: Stage, dtype: int64

In [52]:
opportunities[opportunities['Mailing Address Line 1'].isnull()==False].Stage.value_counts()

Lost                 504
Closed Won           136
Deal Signed           50
Contract Sent         34
Invoice Sent          24
Proposal Sent         23
Qualified Lead        17
Presentation          17
Research/Donation      4
Contract Expired       2
Pilot                  1
Contract Review        1
Name: Stage, dtype: int64

In [22]:
#####################################
#load quotes
quotes = pd.read_csv('quotes.csv')

In [23]:
quotes.shape

(1398, 9)

In [24]:
quotes.head()

,Opportunity ID,Opportunity Name,Close Date,Stage,Bill To Street,Bill To City,Bill To Country,Bill To State/Province,Bill To Zip/Postal Code
0,0061a00000GcQdL,525 Water St SW- CMC Mgmt,3/8/18,Contract Sent,525 Water St SW,Washington,United States,District of Columbia,20024
1,0061a00000Mi8dC,Bozzuto - NJ - Park + Garden,6/30/18,Invoice Sent,1450 Garden St,Hoboken,United States,New Jersey,7030
2,0061a00000M4PAU,Greystar- The Cameron,11/17/17,Deal Signed,8710 Cameron Street,Silver Spring,United States,Maryland,20910
3,0061a00000MgelJ,JLL- 2035 NW Front Ave,1/31/18,Proposal Sent,2035 Front Ave,Portland,United States,Oregon,97209
4,0061a00000KOF8z,International Monetary Fund- Spring Conference,1/31/18,Closed Won,700 19th St NW,"Washington,",United States,District of Columbia,20431

In [25]:
quotes.Stage.value_counts()

Lost                 698
Closed Won           274
Deal Signed          136
Invoice Sent          83
Contract Sent         81
Proposal Sent         79
Presentation          21
Qualified Lead        12
Contract Expired      11
Pilot                  1
Contract Review        1
Research/Donation      1
Name: Stage, dtype: int64

In [78]:
quotes[quotes['Bill To Street'].isnull()==False]

,Opportunity ID,Opportunity Name,Close Date,Stage,Bill To Street,Bill To City,Bill To Country,Bill To State/Province,Bill To Zip/Postal Code
0,0061a00000GcQdL,525 Water St SW- CMC Mgmt,3/8/18,Contract Sent,525 Water St SW,Washington,United States,District of Columbia,20024
1,0061a00000Mi8dC,Bozzuto - NJ - Park + Garden,6/30/18,Invoice Sent,1450 Garden St,Hoboken,United States,New Jersey,7030
2,0061a00000M4PAU,Greystar- The Cameron,11/17/17,Deal Signed,8710 Cameron Street,Silver Spring,United States,Maryland,20910
3,0061a00000MgelJ,JLL- 2035 NW Front Ave,1/31/18,Proposal Sent,2035 Front Ave,Portland,United States,Oregon,97209
4,0061a00000KOF8z,International Monetary Fund- Spring Conference,1/31/18,Closed Won,700 19th St NW,"Washington,",United States,District of Columbia,20431
5,0061a00000KjdaL,National Institute of Health (NIH) 5601 Fisher...,11/1/17,Proposal Sent,5601 Fishers Lane,NaN,United States,NaN,NaN
6,0061a00000Mgpep,GAP HQ- 1 Harrison St,2/2/18,Deal Signed,Two Folsom St,San Francisco,United States,California,94105
8,0061a00000HIaGb,AVB - AVA Theater - Boston,4/1/17,Invoice Sent,45 Stuart Street,Boston,United States,Massachusetts,2116
9,0061a00000Mgdqw,Metro Village- Spring Place- DC,1/30/18,Proposal Sent,"3 Bethesda Metro, Suite 110",Bethesda,United States,Maryland,20814
10,0061a00000M4P5Q,Greystar- Aventine at Fort Totten,11/17/17,Deal Signed,5210 3rd Street NE,Washington,United States,District of Columbia,20011
11,0061a00000M3j9z,Wood Partners- Alta Roosevelt- CHI,10/27/17,Closed Won,801 S. Financial Pl.,Chicago,United States,Illinois,60607
13,0061a00000M3DjE,Oxford Properties- Royal Bank Plaza,12/18/17,Contract Expired,Royal Bank Plaza North Tower,Toronto,Canada,Ontario,M5J2J2
14,0061a00000Kkodx,City of Cambridge- 119 Windsor St- Public Heal...,12/7/17,Deal Signed,344 Broadway,Cambridge,United States,Massachusetts,2139
15,0061a00000M4fhF,The Collective- Bedford SQ,11/14/17,Proposal Sent,14 Bedford Sq.,London,United Kingdom,NaN,WC1B 3JA
16,0061a00000MiHRw,Schupp Comp - Hyatt Place/AUSA,2/22/18,Proposal Sent,2401 Wilson Blvd,Arlington,United States,Virginia,22201
17,0061a00000HyrMf,reThink - Central Florida- FDOT,2/27/18,Deal Signed,250 S Orange Ave\nSuite 200,Orlando,United States,Florida,32801
18,0061a00000Irt5y,Daro Management - The Vintage on 16,2/1/18,Presentation,2929 Connecticut Ave. NW Suite A,Washington,United States,District of Columbia,20008
19,0061a00000M3b3g,Concord Hospitality- Hyatt House Jersey City,10/31/17,Closed Won,"11410 Common Oaks\nRaleigh, NC 27614",NaN,United States,NaN,NaN
22,0061a00000M6ZSv,Konterra- DC- 2611 Jefferson Davis Highway,12/18/17,Proposal Sent,2611 Jefferson Davis Highway,Crystal City,United States,Virginia,NaN
23,0061a00000DJUWm,Seattle Children's Hospital: 12/2017,1/1/18,Closed Won,4800 Sand Point Way NE,Seattle,United States,Washington,98105
24,0061a00000M6FZM,741 Harvard- Indigo Real Estate- SEA,1/9/18,Closed Won,741 Harvard Ave E,Seattle,United States,Washington,98102
25,0061a00000M6FZM,741 Harvard- Indigo Real Estate- SEA,1/9/18,Closed Won,741 Harvard Ave E,Seattle,United States,Washington,98102
26,0061a00000KkYER,Donohoe- MD - 7101 Wisconsin Ave.,3/8/18,Contract Sent,7101 Wisconsin Ave,Bethesda,United States,Maryland,20814
27,0061a00000M5oXh,Carrolsburg: A Condominium- DC,12/6/17,Lost,1250 4th St SW,Washington,United States,District of Columbia,20024
29,0061a00000KkYER,Donohoe- MD - 7101 Wisconsin Ave.,3/8/18,Contract Sent,7101 Wisconsin Ave,Bethesda,United States,Maryland,20814
30,0061a00000KkG0w,Modera Sandy Springs- ATL,9/26/17,Lost,6125 Roswell Rd,Atlanta,United States,Georgia,30309
33,0061a00000KkY0j,Greystar- The Aspen- 1031 4th Street LLC,10/3/17,Closed Won,1011 4th St NW,Washington,United States,District of Columbia,20001
34,0061a00000DJUWe,O'Neill Properties - PHL - Royal Athena,12/1/17,Invoice Sent,600 Righters Ferry Rd,Bala Cynwyd,United States,Pennsylvania,NaN
35,0061a00000IuzTB,MRP - 3101 Wilson HART Hartford Bldg LLC,1/1/18,Presentation,3101 Wilson BLVD,Arlington,United States,Virginia,22201
36,0061a00000M3IGy,1155 Connecticut Ave NW- Cushman,11/30/17,Contract Sent,1155 Connecticut Ave NW,Washington,United States,District of Columbia,20036
...,...,...,...,...,...,...,...,...,...
1363,0061a00000KM4FT,Goldrich Kest - Museum Tower - LA,1/31/18,Lost,225 S Olive St,Los Angeles,United States,California,90012
1364,0061a00000M5eFM,Quadrangle - DC - The Lurgan,12/18/17,Deal Signed,915 L St NW,Washington,United States,District of Columbia,20001
1365,0061a00000Mfhn9,Tysons Partnership - McLean - Gannett,2/14/18,Invoice Sent,1750 Tysons Blvd \nSuite 1500\nAttn: Matt Smith,Tysons,United States,Virginia,22102
1366,0061a00000M5t1E,LCOR - The Altaire - Crystal City VA,12/18/17,Deal Signed,400 Army Navy Drive,Arlington,United States,Virginia,22203
1368,0061a00000M4OOF,Gates Hudson - Arlington - Crystal Towers,1/31/18,Lost,1600 S Eads St,Arlington,United States,Virginia,22202
1370,0061a00000MhsvJ,Somerset Development - DC - Portner Flats,2/28/18,Deal Signed,"Portner Flats, LLC\nc/o Eagle Point Management...",South Portland,United States,Maine,4106
1371,0061a00000Kk52U,Greystar- Austin - Platform,1/31/18,Lost,"18 Broad St, Ste 300",Charleston,United States,South Carolina,29401
1372,0061a00000MhsvJ,Somerset Development - DC - Portner Flats,2/28/18,Deal Signed,"5101 Wisconsin Ave NW, Suite 410",Washington,United States,District of Columbia,20016
1373,0061a00000M6GyN,Borger Properties - DC - Dorchester House,1/30/18,Deal Signed,2480 16th St NW,Washington,United States,District of Columbia,20009
1374,0061a00000Mfopp,Mill Creek - DC - Modern on M,3/31/18,Contract Sent,425 M St SW,Washington,United States,District of Columbia,20024
1375,0061a00000M5G3z,Homewood Suites Arlington Rosslyn Key Bridge,1/31/18,Lost,1900 North Quinn Street,Arlingotn,United States,Virginia,22209
1376,0061a00000M5MQt,Shooshan Company - Arlington - The Rixey,12/8/17,Invoice Sent,"4075 Wilson Blvd., Suite 440",Arlignton,United States,NaN,22203
1378,0061a00000KOPia,Movability - 221 E 7th St,8/18/17,Lost,221 E 7th St,Austin,United States,Texas,78701
1379,0061a00000JsGoY,Cushman & Wakefield - Lafayette Centre,3/30/18,Contract Review,"1120 20th Street NW, \nSuite 100-S",Washington,United States,District of Columbia,20036
1380,0061a00000Mi08e,Bet Investments - Dulles - The Mark at Dulles ...,3/31/18,Contract Sent,2323 Dulles Station Blvd.,Herndon,United States,Virginia,2171
1381,0061a00000ItBge,100 Capitol Yards - Bozzuto - DC,12/20/17,Closed Won,100 I St SE,Washington,United States,District of Columbia,20003
1382,0061a00000M6C9B,Wilshire Park Condominium - DC,1/12/18,Lost,3701 Connecticut Ave NW,Washington,United States,District of Columbia,20008
1383,0061a00000MgixA,Horning Brothers - DC - Stanton Commons,2/22/18,Deal Signed,"3333 14th Street, NW, Suite 300\n\nAttn: Leke...",Washington,United States,District of Columbia,20010
1384,0061a00000MhoY2,Cushman & Wakefield - DC - 200 Mass Ave,3/31/18,Contract Sent,200 Massachusetts Ave NW,Washington,United States,District of Columbia,20001
1385,0061a00000M5iSH,Camden - DC - Camden Grand Parc,2/28/18,Lost,910 15th St NW,Washington,United States,District of Columbia,20005
1386,0061a00000KOLvZ,Greystar - Next on 6th - LA-,8/31/17,Closed Won,17885 Von Karman Avenue \nSuite 450,Irvine,United States,California,92614
1387,0061a00000KNVHG,United Therapeutics- Silver Spring Office,3/31/18,Contract Sent,1040 Spring St,Silver Spring,United States,Maryland,20910
1388,0061a00000KNSpS,Dinerstein - Millennium Mission Valley - San D...,12/25/17,Lost,777 S Hwy. 101 Suite 210,Solana Beach,United States,California,92075
1389,0061a00000LSSno,MRP - 1411 K Street NW,1/31/18,Lost,1411 K St NW,Washington,United States,District of Columbia,20005
1390,0061a00000LSSl5,"MRP - 1333 H St, NW",1/31/18,Lost,"1333 H Street, NW",Washington,United States,District of Columbia,20005
1391,0061a00000Hx7Oy,Traffic Engineers Inc - HOU,1/30/17,Lost,801 Congress Ave.\n#325,Houston,United States,Texas,77002
1392,0061a00000KNHEA,University of Houston- Houston,9/29/17,Lost,5000 GULF FWY \nBLDG 2 RM 131,Houston,United States,Texas,77204-6036
1393,0061a00000HxgOR,Tanger Outlets - National Harbor Mall (MD),3/31/18,Contract Sent,6800 Oxon Hill Rd,National Harbor,United States,Maryland,20745
1394,0061a00000JqLIz,Vornado - 1717 K Street NW - DC,7/6/17,Lost,"1717 K St NW, Suite 100",Washington,United States,District of Columbia,20006
1395,0061a00000ItBge,100 Capitol Yards - Bozzuto - DC,12/20/17,Closed Won,100 Capitol Yards,Washington,United States,NaN,20003

In [55]:
quotes.columns

Index(['Opportunity ID', 'Opportunity Name', 'Close Date', 'Stage',
       'Bill To Street', 'Bill To City', 'Bill To Country',
       'Bill To State/Province', 'Bill To Zip/Postal Code'],
      dtype='object')

In [156]:
#########################################
#How many Opportunity records are in quote?
opportunities.merge(quotes, on='Opportunity ID', how = 'inner').shape

(1322, 22)

In [74]:
#look at the matching records, see if they make sense
opportunities.merge(quotes, on='Opportunity ID')
#looks ok, but a surprising number have

,Opportunity ID,Opportunity Name_x,Close Date_x,Created Date,Stage_x,Billing Address Line 1,Billing Address Line 2,Billing Address Line 3,Mailing Address Line 1,Mailing Address Line 2,Opp Billing Address,Opp Billing Address 2,Opportunity Name_y,Close Date_y,Stage_y,Bill To Street,Bill To City,Bill To Country,Bill To State/Province,Bill To Zip/Postal Code
0,0061a00000G3m29,The Wolff Company - Portfolio,3/30/17,7/20/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Wolff Company - Portfolio,3/30/17,Lost,NaN,NaN,United States,NaN,NaN
1,0061a00000IuMzU,Pittsburgh Sports & Exhibition Authority - PIT...,8/2/17,4/13/17,Lost,171 10th St.,NaN,NaN,200 Ross St.,4th Fl.,NaN,NaN,Pittsburgh Sports & Exhibition Authority - PIT...,8/2/17,Lost,171 10th St.,Pittsburgh,United States,Pennsylvania,15222
2,0061a00000Iuzsa,CBRE / GE - San Ramon - GE Digital Office,5/31/17,5/1/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBRE / GE - San Ramon - GE Digital Office,5/31/17,Lost,NaN,NaN,United States,NaN,NaN
3,0061a00000HyoAr,Brookfield - TBD,5/31/17,2/12/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brookfield - TBD,5/31/17,Lost,"Level 23, 135 King Street,",Sydney,Australia,New South Wales,2000
4,0061a00000HyoAr,Brookfield - TBD,5/31/17,2/12/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brookfield - TBD,5/31/17,Lost,"Level 23, 135 King Street,",Sydney,Australia,New South Wales,2000
5,0061a00000Gce3l,Hanover Company - DEN - TBD,10/28/16,9/26/16,Lost,NaN,NaN,NaN,"5847 San Felipe, Suite 3600",NaN,NaN,NaN,Hanover Company - DEN - TBD,10/28/16,Lost,"5847 San Felipe, Suite 3600","Houston, Texas Area",United States,Texas,77057
6,0061a00000Gce3l,Hanover Company - DEN - TBD,10/28/16,9/26/16,Lost,NaN,NaN,NaN,"5847 San Felipe, Suite 3600",NaN,NaN,NaN,Hanover Company - DEN - TBD,10/28/16,Lost,"5847 San Felipe, Suite 3600",Houston,United States,Texas,77057
7,0061a00000IuO8q,ConAm Group- SEA - Parla Apartments,5/1/17,4/13/17,Invoice Sent,3990 Ruffin Rd Ste 100,NaN,NaN,3990 Ruffin Rd Ste 100,NaN,NaN,NaN,ConAm Group- SEA - Parla Apartments,5/1/17,Invoice Sent,3990 Ruffin Rd Ste 100,San Diego,United States,California,92123-4805
8,0061a00000IuSsn,Atlassian-Soma Offices,5/19/17,4/17/17,Closed Won,1098 Harrison St.,NaN,NaN,NaN,NaN,NaN,NaN,Atlassian-Soma Offices,5/19/17,Closed Won,1098 Harrison St.,San Francisco,United States,California,94103
9,0061a00000ItjwO,Winexburg Manor,6/30/17,3/30/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winexburg Manor,6/30/17,Lost,2301 Glenallan Ave,Silver Spring,United States,Maryland,20906
10,0061a00000Hv5Bq,"Monday Properties- 1000-1100 Wilson Owner, LLC",1/27/17,12/1/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Monday Properties- 1000-1100 Wilson Owner, LLC",1/27/17,Lost,1000 Wilson Boulevard\nSuite 700,Arlington,United States,Virginia,22209
11,0061a00000Hv5Bq,"Monday Properties- 1000-1100 Wilson Owner, LLC",1/27/17,12/1/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Monday Properties- 1000-1100 Wilson Owner, LLC",1/27/17,Lost,1000 Wilson Boulevard\nSuite 700,Arlington,United States,Virginia,22209
12,0061a00000HHUUr,Malibu Investments Inc - 9 Tippet - TORONTO,4/27/17,11/7/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Malibu Investments Inc - 9 Tippet - TORONTO,4/27/17,Lost,"130 Spadina Ave., Suite 707",Toronto,Canada,Ontario,M5V 2L4
13,0061a00000MfWGk,Equity Residential - Springline - SEA,1/31/18,1/11/18,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Equity Residential - Springline - SEA,1/31/18,Lost,3220 California SW,Seattle,United States,Washington,98116
14,0061a00000Fock7,Bozzuto - Portfolio,7/31/17,5/24/16,Lost,6406 Ivy Ln Ste 700,NaN,NaN,6406 Ivy Lane,Suite 700,6406 Ivy Lane,Suite 700,Bozzuto - Portfolio,7/31/17,Lost,NaN,New York,United States,NaN,NaN
15,0061a00000Jr0Fe,Pitt Pilot Addendum 2 - Carnegie Library,8/16/17,5/18/17,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pitt Pilot Addendum 2 - Carnegie Library,8/16/17,Closed Won,NaN,NaN,United States,NaN,NaN
16,0061a00000HEtKB,Pittsburgh Pilot - Phase 1,3/1/17,10/4/16,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pittsburgh Pilot - Phase 1,3/1/17,Closed Won,NaN,NaN,United States,NaN,NaN
17,0061a00000HEtKB,Pittsburgh Pilot - Phase 1,3/1/17,10/4/16,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pittsburgh Pilot - Phase 1,3/1/17,Closed Won,NaN,NaN,United States,NaN,NaN
18,0061a00000HEtKB,Pittsburgh Pilot - Phase 1,3/1/17,10/4/16,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pittsburgh Pilot - Phase 1,3/1/17,Closed Won,NaN,NaN,NaN,NaN,NaN
19,0061a00000HEtKB,Pittsburgh Pilot - Phase 1,3/1/17,10/4/16,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pittsburgh Pilot - Phase 1,3/1/17,Closed Won,NaN,NaN,NaN,NaN,NaN
20,0061a00000HEtKB,Pittsburgh Pilot - Phase 1,3/1/17,10/4/16,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pittsburgh Pilot - Phase 1,3/1/17,Closed Won,NaN,NaN,United States,NaN,NaN
21,0061a00000HEtKB,Pittsburgh Pilot - Phase 1,3/1/17,10/4/16,Closed Won,UPMC - Parkvale Building,200 Meyran Ave.,NaN,NaN,NaN,NaN,NaN,Pittsburgh Pilot - Phase 1,3/1/17,Closed Won,NaN,NaN,NaN,NaN,NaN
22,0061a00000KOXH2,Wharf Piers 3 & 4 - PN Hoffman,8/24/17,8/22/17,Deal Signed,680 Water St SW,NaN,NaN,NaN,NaN,NaN,NaN,Wharf Piers 3 & 4 - PN Hoffman,8/24/17,Deal Signed,680 Water St SW,Washington,United States,District of Columbia,20024
23,0061a00000M4GUD,JLL - SF - 580 California,12/31/17,11/6/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JLL - SF - 580 California,12/31/17,Lost,580 California Street,San Francisco,United States,California,94104
24,0061a00000ItEiv,Vornado (JBGSMITH) - CC Underground - Shops @ ...,8/4/17,3/19/17,Lost,1901 S. Bell Street,NaN,NaN,1901 S. Bell Street,NaN,NaN,NaN,Vornado (JBGSMITH) - CC Underground - Shops @ ...,8/4/17,Lost,"1901 S. Bell Street,\nSuite 150",Arlington,United States,Virginia,22202
25,0061a00000KNYnl,Vornado (JBGSMITH) - CC Underground - Shops @ ...,10/31/17,8/2/17,Lost,1901 S. Bell Street,NaN,NaN,NaN,NaN,NaN,NaN,Vornado (JBGSMITH) - CC Underground - Shops @ ...,10/31/17,Lost,"1901 S. Bell Street, \nSuite 150",Arlington,United States,Virginia,22202
26,0061a00000GFwbf,Mill Creek (Chris Winchester) - Modera Observa...,12/20/16,8/12/16,Closed Won,6110 Executive Boulevard,Suite 315,NaN,NaN,NaN,NaN,1290 Broadway Street,Mill Creek (Chris Winchester) - Modera Observa...,12/20/16,Closed Won,1290 Broadway Street,Denver,United States,Colorado,80203
27,0061a00000HyRoJ,Binghamton- Binghamton U (SUNY),6/6/17,2/6/17,Closed Won,PO BOX 6000,NaN,NaN,PO BOX 6000,NaN,NaN,NaN,Binghamton- Binghamton U (SUNY),6/6/17,Closed Won,4400 Vestal Parkway East,Binghampton,United States,New York,13902
28,0061a00000HyFVN,Just Business,2/13/17,2/1/17,Lost,2225 3RD STREET,NaN,NaN,NaN,NaN,NaN,NaN,Just Business,2/13/17,Lost,2225 3RD STREET,SAN FRANCISCO,United States,California,94107
29,0061a00000IryMd,Ian Schrager Company-Public Hotels,4/4/17,2/23/17,Lost,215 Chrystie St,NaN,NaN,NaN,NaN,NaN,NaN,Ian Schrager Company-Public Hotels,4/4/17,Lost,215 Chrystie St,New York,United States,New York,10002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292,0061a00000FruOs,Hornblower - NYC,11/30/16,6/12/16,Lost,NaN,NaN,NaN,Hornblower Citywide Ferry,110 Wall St.,NaN,NaN,Hornblower - NYC,11/30/16,Lost,NaN,NaN,United States,NaN,NaN
1293,0061a00000HvqUr,Reading Terminal Market - PHL,1/12/17,12/14/16,Closed Won,51 N 12th St,NaN,NaN,1136 Arch St.,Unit 400,NaN,NaN,Reading Terminal Market - PHL,1/12/17,Closed Won,1136 Arch St.\nUnit 400,Philadelphia,United States,Pennsylvania,19107
1294,0061a00000DTA4z,Reading Terminal Market - PHL,11/30/16,1/7/16,Lost,51 N 12th St,NaN,NaN,1136 Arch St.,Unit 400,NaN,NaN,Reading Terminal Market - PHL,11/30/16,Lost,51 N 12th St,Philadelphia,United States,Pennsylvania,19107
1295,0061a00000DUKA7,Volunteers of America - NYC - Wales Ave.,9/30/16,1/15/16,Lost,340 West 85th Street,NaN,NaN,340 West 85th St.,NaN,592 Wales Avenue,NaN,Volunteers of America - NYC - Wales Ave.,9/30/16,Lost,340 West 85th Street,New York,United States,New York,10024-3800
1296,0061a00000Kk2ck,Midtown Alliance - ATL - Membership,9/20/17,9/20/17,Lost,999 Peachtree St.,Ste. 730,NaN,NaN,NaN,NaN,NaN,Midtown Alliance - ATL - Membership,9/20/17,Lost,NaN,Atlanta,United States,Georgia,NaN
1297,0061a00000HG7tL,Whole Foods Market - Union Square/Tribecca Pil...,1/1/18,10/21/16,Proposal Sent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Whole Foods Market - Union Square/Tribecca Pil...,1/1/18,Proposal Sent,NaN,NaN,United States,NaN,NaN
1298,0061a00000HG7tL,Whole Foods Market - Union Square/Tribecca Pil...,1/1/18,10/21/16,Proposal Sent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Whole Foods Market - Union Square/Tribecca Pil...,1/1/18,Proposal Sent,NaN,NaN,United States,NaN,NaN
1299,0061a00000HH3J2,Facebook Seattle - 2016,11/11/16,11/1/16,Lost,NaN,NaN,NaN,1101 Dexter Ave North,NaN,NaN,NaN,Facebook Seattle - 2016,11/11/16,Lost,NaN,NaN,NaN,NaN,NaN
1300,0061a00000KMGi4,Facebook Seattle - 1101 Dexter Ave - 2017,8/3/17,7/3/17,Lost,NaN,NaN,NaN,1101 Dexter Ave North,NaN,NaN,NaN,Facebook Seattle - 1101 Dexter Ave - 2017,8/3/17,Lost,1101 Dexter Avenue,Seattle,United States,Washington,NaN
1301,0061a00000AcNLc,City of San Jose City Hall,12/31/17,6/15/15,Lost,200 E Santa Clara St,NaN,NaN,NaN,NaN,NaN,NaN,City of San Jose City Hall,12/31/17,Lost,200 E Santa Clara St,San Jose,United States,California,95113
1302,0061a00000Kkodx,City of Cambridge- 119 Windsor St- Public Heal...,12/7/17,10/6/17,Deal Signed,344 Broadway,NaN,NaN,NaN,NaN,NaN,NaN,City of Cambridge- 119 Windsor St- Public Heal...,12/7/17,Deal Signed,344 Broadway,Cambridge,United States,Massachusetts,2139
1303,0061a00000M4wAj,Google - SF - 345 Spear,4/30/18,11/17/17,Presentation,345 Spear Street,NaN,NaN,NaN,NaN,NaN,NaN,Google - SF - 345 Spear,4/30/18,Presentation,345 Spear Street,San Francisco,United States,California,94105
1304,0061a00000GTfvO,Palantir - Multi Office Expansion,10/31/16,9/13/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Palantir - Multi Office Expansion,10/31/16,Lost,NaN,NaN,United States,NaN,NaN
1305,0061a00000G4nQE,Starlight Investments - GTA - TORONTO,4/27/17,7/28/16,Lost,3300 Bloor St West,NaN,NaN,NaN,NaN,NaN,NaN,Starlight Investments - GTA - TORONTO,4/27/17,Lost,3300 Bloor St West,Toronto,Canada,Ontario,M8X 2X2
1306,0061a00000IrpIP,Hines - San Mateo - 400/450 Concar,7/31/17,2/21/17,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hines - San Mateo - 400/450 Concar,7/31/17,Lost,NaN,NaN,United States,NaN,NaN
1307,0061a00000Gcq7n,Transpo Group - HQ - Seattle,9/30/16,9/29/16,Invoice Sent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transpo Group - HQ - Seattle,9/30/16,Invoice Sent,12131 113th Ave NE #203,Kirkland,United States,Washington,98034
1308,0061a00000Gcq7n,Transpo Group - HQ - Seattle,9/30/16,9/29/16,Invoice Sent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transpo Group - HQ - Seattle,9/30/16,Invoice Sent,12131 113th Ave NE #203,Kirkland,United States,Washington,98034
1309,0061a000003Uu5B,UC Berkeley 15-16,4/15/15,5/19/15,Closed Won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UC Berkeley 15-16,4/15/15,Closed Won,NaN,Berkeley,United States,California,NaN
1310,0061a000003Uu5B,UC Berkeley 15-16,4/15/15,5/19/15,Closed Won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UC Berkeley 15-16,4/15/15,Closed Won,NaN,Berkeley,United States,California,NaN
1311,0061a00000IrfG2,1111 Broadway - Oakland - Lionstone,4/30/18,2/17/17,Presentation,100 Waugh Drive,NaN,NaN,NaN,NaN,NaN,NaN,1111 Broadway - Oakland - Lionstone,4/30/18,Presentation,100 Waugh Drive,Houston,United States,Texas,77007
1312,0061a00000MfNBo,Greystar - Wheaton - The George,3/6/18,1/10/18,Contract Sent,1101 Connecticut Ave NW,NaN,NaN,NaN,NaN,NaN,NaN,Greystar - Wheaton - The George,3/6/18,Contract Sent,1101 Connecticut Ave NW,Washington,United States,District of Columbia,20036
1313,0061a00000FrIb0,GPI- Santa Monica - LA,1/23/17,6/8/16,Invoice Sent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GPI- Santa Monica - LA,1/23/17,Invoice Sent,"11777 San Vicente Blvd., Suite 550",Los Angeles,United States,California,90049
1314,0061a00000JriFf,AVB - AVA Little Tokyo - CA - TS Lite,1/8/18,6/7/17,Invoice Sent,236 S Los Angeles Street,NaN,NaN,NaN,NaN,NaN,NaN,AVB - AVA Little Tokyo - CA - TS Lite,1/8/18,Invoice Sent,236 S Los Angeles Street,Los Angeles,United States,California,90012
1315,0061a00000Gcqit,CIVIQ - San Antonio - Pilot,11/30/16,9/29/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIVIQ - San Antonio - Pilot,11/30/16,Lost,NaN,NaN,United States,NaN,NaN
1316,0061a00000GcqrG,CIVIQ - Dallas - Pilot,12/8/16,9/29/16,Lost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIVIQ - Dallas - Pilot,12/8/16,Lost,NaN,NaN,United States,NaN,NaN
1317,0061a00000B1tAd,Symantec HQ,4/3/17,8/4/15,Lost,350 Ellis Street,NaN,NaN,NaN,NaN,NaN,NaN,Symantec HQ,4/3/17,Lost,350 Ellis Street,Mountain View,United States,California,94043
1318,0061a00000Mfp4k,Fairfield - The Eugene- Manhattan West NYC- CM...,1/17/18,1/17/18,Proposal Sent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairfield - The Eugene- Manhattan West NYC- CM...,1/17/18,Proposal Sent,NaN,New York,United States,New York,NaN
1319,0061a00000FqSae,Fairfield - The Eugene- Manhattan West NYC,2/25/17,6/3/16,Closed Won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairfield - The Eugene- Manhattan West NYC,2/25/17,Closed Won,NaN,NaN,United States,NaN,NaN
1320,0061a00000KM2IS,Lincoln Property Company - BOS - The Edison,7/12/17,6/27/17,Deal Signed,Lincoln Cooper Street LLC,221 Crescent St.,Suite 102A,221 Crescent Street,Suite 102A,NaN,NaN,Lincoln Property Company - BOS - The Edison,7/12/17,Deal Signed,221 Crescent St.\nSuite 102A,Waltham,United States,Massachusetts,2453
1321,0061a00000AXNHM,JBG - Fort Totten - DC,10/1/14,6/9/15,Closed Won,300 Riggs Road NE,NaN,NaN,NaN,NaN,NaN,NaN,JBG - Fort Totten - DC,10/1/14,Closed Won,300 Riggs Road NE,Washington,United States,District of Columbia,20011

In [89]:
quotes[quotes['Opportunity ID']=='0061a00000G3jSG']

Empty DataFrame
Columns: [Opportunity ID, Opportunity Name, Close Date, Stage, Bill To Street, Bill To City, Bill To Country, Bill To State/Province, Bill To Zip/Postal Code]
Index: []

In [ ]:
#what about the ones without addresses

In [70]:
opp_no_address = opportunities[opportunities['Billing Address Line 1'].isnull()]

In [72]:
opp_no_address.shape

(1363, 12)

In [73]:
opp_no_address.merge(quotes, on='Opportunity ID').shape

(606, 20)

In [79]:
#total missing addresses:
print(2499 - 1322 + 230)

1407

In [26]:
################################
#load leads
leads = pd.read_csv('leads.csv')

In [27]:
leads.head()

,Lead ID,First Name,Last Name,Lead Source,Lead Status,Street,City,State/Province,Zip/Postal Code,Country
0,00Q1a00000Lqb3V,Audrey,McStraw,NaN,Contacted,1st Floor,Belfast County Antrim,NaN,NaN,United States
1,00Q1a00000Lqb3W,Roscoe,Chubb,NaN,Contacted,Embassy House Queens Avenue,Bristol Avon,NaN,NaN,United States
2,00Q1a00000Lqb3X,Robert,Grant,NaN,Contacted,Wemyss House 8 Wemyss Place,Edinburgh Midlothian,NaN,NaN,United States
3,00Q1a00000LHtQ2,Paul,Dutko,NaN,Contacted,8601 Georgia Ave Ste 200,Silver Spring,Maryland,20910-3438,United States
4,00Q1a00000I1an7,Dermot,Sweeny,NaN,Contacted,468 Wellington St W,Toronto,Ontario,M5V 1E3,Canada

In [34]:
leads.shape

(17063, 10)

In [59]:
leads[leads['Street'].isnull()]

Empty DataFrame
Columns: [Lead ID, First Name, Last Name, Lead Source, Lead Status, Street, City, State/Province, Zip/Postal Code, Country]
Index: []

In [32]:
leads['Lead Status'].value_counts().head(8)

Contacted      11647
Open            2261
Unqualified     2065
Qualified        844
Future           152
ITEM insert       10
499                1
38                 1
Name: Lead Status, dtype: int64

In [33]:
leads['Lead Source'].value_counts()

BD Outreach           2198
Sales Outreach         570
MailChimp              143
External Referral      141
Web                     62
Seminar - Partner       58
Inbound                 46
Trade Show              40
Employee Referral       37
Other                   24
Word of mouth            9
Website Order Form       6
Live Chat                5
Partner                  4
Public Relations         3
Seminar - Internal       2
Repeat Business          2
Name: Lead Source, dtype: int64

In [60]:
leads.columns

Index(['Lead ID', 'First Name', 'Last Name', 'Lead Source', 'Lead Status',
       'Street', 'City', 'State/Province', 'Zip/Postal Code', 'Country'],
      dtype='object')

In [90]:
quotes.columns

Index(['Opportunity ID', 'Opportunity Name', 'Close Date', 'Stage',
       'Bill To Street', 'Bill To City', 'Bill To Country',
       'Bill To State/Province', 'Bill To Zip/Postal Code'],
      dtype='object')

In [ ]:
########################
#merge quotes and opportunities
################################

In [96]:
#concatenate quote address
quotes['Address'] = quotes['Bill To Street']+' '+quotes['Bill To City']+' '+quotes['Bill To Country']+' '+quotes['Bill To State/Province']+' '+quotes['Bill To Zip/Postal Code']

In [99]:
#quotes.head()

In [103]:
opportunities.columns

Index(['Opportunity ID', 'Opportunity Name', 'Close Date', 'Created Date',
       'Stage', 'Billing Address Line 1', 'Billing Address Line 2',
       'Billing Address Line 3', 'Mailing Address Line 1',
       'Mailing Address Line 2', 'Opp Billing Address',
       'Opp Billing Address 2'],
      dtype='object')

In [115]:
#concatenate opportunities address
#opportunities['']+' '+
#not using this because we don't want to create incomplete addresses
#opportunities['Billing Address Line 1']+' '+opportunities['Billing Address Line 2']+' '+opportunities['Billing Address Line 3']
opportunities['Address'] = np.nan

In [117]:
#opportunities.head()

In [ ]:
#change both data frames to have the same column names
#new columns = id, name, close_date, stage, address

In [131]:
new_cols = ['id', 'name', 'close_date', 'stage', 'address']

In [132]:
opp = opportunities[['Opportunity ID','Opportunity Name','Close Date','Stage','Address']]

In [133]:
opp.columns = new_cols

In [139]:
#opp.head()

,id,name,close_date,stage,address
0,0061a00000GFpPA,Paradigm Properties LLC -TBD,9/30/16,Lost,NaN
1,0061a00000GFwVj,Macklowe Properties - NYC - 1 Wall St.,9/30/16,Lost,NaN
2,0061a00000G3m29,The Wolff Company - Portfolio,3/30/17,Lost,NaN
3,0061a00000IuoBv,Paradigm Companies- Portfolio,6/30/17,Lost,NaN
4,0061a00000IuMzU,Pittsburgh Sports & Exhibition Authority - PIT...,8/2/17,Lost,NaN

In [136]:
quo = quotes[['Opportunity ID','Opportunity Name','Close Date','Stage','Address']]

In [137]:
quo.columns = new_cols

In [140]:
#quo.head()

In [174]:
#from opp, remove records that are in quo
def in_quo(id):
    if id in quo.id.values:
        return True
    else:
        return False

In [175]:
opp.id.apply(in_quo).value_counts()

False    1430
True     1069
Name: id, dtype: int64

In [178]:
opp2 = opp[opp.id.apply(in_quo)==False]

In [181]:
#opp2.head()

In [184]:
#append the two dataframes
df = quo.append(opp2, ignore_index=True)

In [206]:
df.shape

(2828, 5)

In [ ]:
#check for duplicates

In [212]:
df.id.value_counts().head(10)

0061a00000HEtKB    6
0061a00000M331e    5
0061a00000HGxoR    4
0061a00000HHJCY    4
0061a00000KOTaQ    4
0061a00000HEydp    4
0061a00000JsHgq    4
0061a00000KLw35    4
0061a00000Kkge3    4
0061a00000G4484    4
Name: id, dtype: int64

In [221]:
df[df.id=='0061a00000KN2II']

,id,name,close_date,stage,address
238,0061a00000KN2II,Bureau of National Affairs (BNA)- Arlington an...,12/5/17,Deal Signed,1801 South Bell Street Arlington United States...
248,0061a00000KN2II,Bureau of National Affairs (BNA)- Arlington an...,12/5/17,Deal Signed,1801 S Bell St. Arlington United States Virgin...

In [213]:
df.shape

(2828, 5)

In [214]:
df.drop_duplicates().shape

(2644, 5)

In [215]:
df.drop_duplicates(inplace=True)

In [216]:
df.shape

(2644, 5)

In [224]:
#about df.id.value_counts().head(100)   #about 90 records w/ value count > 1

In [225]:
df.drop_duplicates(subset=['id'], keep='last',inplace=True)

In [226]:
df.shape

(2558, 5)

In [227]:
print ('total:', df.shape[0])
print ('with full address:', df[df['address'].isnull()==False].shape[0])
print ('missing/incomplete addresses:', df[df['address'].isnull()==True].shape[0])

total: 2558
with full address: 893
missing/incomplete addresses: 1665

In [229]:
leads[leads['Lead ID']=='0061a00000GFPd7']

Empty DataFrame
Columns: [Lead ID, First Name, Last Name, Lead Source, Lead Status, Street, City, State/Province, Zip/Postal Code, Country]
Index: []